force-app/main/default/objects/Access_Code_Settings__mdt/Access_Code_Settings__mdt.object-meta.xml
<CustomObject>
  <description>Stores the planet codes and its access codes.</description>
  <label>Access Code Settings</label>
  <pluralLabel>Access Codes Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Access_Code_Settings__mdt/fields/Access_Code__c.field-meta.xml
<CustomField>
  <description>Stores the Access Codes for scanning a Planet. E.g. jPnR\5625, t$Th\5199, etc.</description>
  <fullName>Access_Code__c</fullName>
  <inlineHelpText>Stores the Access Codes for scanning a Planet. E.g. jPnR\5625, t$Th\5199, etc.</inlineHelpText>
  <label>Access Code</label>
  <length>20</length>
  <required>true</required>
  <type>Text</type>
</CustomField>

force-app/main/default/objects/Access_Code_Settings__mdt/fields/Planet_Code__c.field-meta.xml
<CustomField>
  <description>Stores a Planet Code equivalent to the External Id field used in the Planet custom object.</description>
  <fullName>Planet_Code__c</fullName>
  <inlineHelpText>Stores a Planet Code equivalent to the External Id field used in the Planet custom object.</inlineHelpText>
  <label>Planet Code</label>
  <length>10</length>
  <required>true</required>
  <type>Text</type>
  <unique>true</unique>
</CustomField>

force-app/main/default/objects/Integration_Credential__mdt/Integration_Credential__mdt.object-meta.xml
<CustomObject>
  <description>Stores the endpoint, security type, user and password used by integrations.</description>
  <label>Integration Credential</label>
  <pluralLabel>Integration Credentials</pluralLabel>
</CustomObject>

force-app/main/default/objects/Integration_Credential__mdt/fields/EndPoint__c.field-meta.xml
<CustomField>
  <description>Stores the endpoint URL for the integration credentials.</description>
  <fullName>EndPoint__c</fullName>
  <inlineHelpText>Stores the endpoint URL for the integration credentials.</inlineHelpText>
  <label>EndPoint</label>
  <length>80</length>
  <required>true</required>
  <type>Text</type>
</CustomField>

force-app/main/default/objects/Integration_Credential__mdt/fields/Password__c.field-meta.xml
<CustomField>
  <description>Stores the password for the integration credentials.</description>
  <fullName>Password__c</fullName>
  <inlineHelpText>Stores the password for the integration credentials.</inlineHelpText>
  <label>Password</label>
  <length>80</length>
  <required>true</required>
  <type>Text</type>
</CustomField>

force-app/main/default/objects/Integration_Credential__mdt/fields/Type__c.field-meta.xml
<CustomField>
  <description>Determines the type of encoding used by the integration. E.g. Basic.</description>
  <fullName>Type__c</fullName>
  <inlineHelpText>Determines the type of encoding used by the integration. E.g. Basic.</inlineHelpText>
  <label>Type</label>
  <length>80</length>
  <required>true</required>
  <type>Text</type>
</CustomField>

force-app/main/default/objects/Integration_Credential__mdt/fields/User__c.field-meta.xml
<CustomField>
  <description>Stores the username for the integration credentials.</description>
  <fullName>User__c</fullName>
  <inlineHelpText>Stores the username for the integration credentials.</inlineHelpText>
  <label>User</label>
  <length>80</length>
  <required>true</required>
  <type>Text</type>
</CustomField>

force-app/main/default/classes/SingletonMandalorianServerAuth.cls
//Testclass: MandalorianServerAPIHandlerTest
public class SingletonMandalorianServerAuth {
  public String Endpoint { get; private set; }
  public String Password { get; private set; }
  public String Type { get; private set; }
  public String User { get; private set; }
  public Map<String, Access_Code_Settings__mdt> AccessCodes { get; private set; }
  private static SingletonMandalorianServerAuth instance = null;

  public SingletonMandalorianServerAuth() {
    initCredentials();
    initPlanetAccessCodes();
  }

  public static SingletonMandalorianServerAuth getInstance() {
    if (instance == null)
      instance = new SingletonMandalorianServerAuth();
    return instance;
  }

  private void initCredentials() {
    List<Integration_Credential__mdt> data = [
      SELECT Id, EndPoint__c, Password__c, Type__c, User__c
      FROM Integration_Credential__mdt
      WHERE Label = 'Mandalorian-Server'
      LIMIT 1
    ];
    if (data.size() != 1)
      return;
    Endpoint = data[0].EndPoint__c;
    Type = data[0].Type__c;
    User = data[0].User__c;
    Password = data[0].Password__c;
  }

  private void initPlanetAccessCodes() {
    AccessCodes = new Map<String, Access_Code_Settings__mdt>();
    List<Access_Code_Settings__mdt> data = [SELECT Id, Planet_Code__c, Access_Code__c FROM Access_Code_Settings__mdt];
    for (Access_Code_Settings__mdt elem : data) {
      AccessCodes.put(elem.Planet_Code__c, elem);
    }
  }

  @testVisible
  private void setAuthDataNull() {
    Endpoint = null;
    Type = null;
    User = null;
    Password = null;
  }
}